language: java

jdk:
    - oraclejdk8

script:
    - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id: AKIAJULQTGCTVH53SMOQ
  secret_access_key: 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
  bucket: a2-proofguru
  skip_cleanup: true
  local-dir: src/amazonS3
  region: us-east-1
